try {
    a = 0;
    console.log(program);
    console.log("program ran successfully");
} catch (err) {
    console.log("this is an error");
}
finally_
console.log("I am a good");
